{{- if and .Values.web.offloadmq.url .Values.web.offloadmq.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: dialogic-secret
type: Opaque
stringData:
  offloadmq-api-key: {{ .Values.web.offloadmq.apiKey | quote }}
{{- end }}
